# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
